endpoints:
  - name: Game
    type: minecraft
  - name: IRC
    type: irc
    extra:
      bot: bot
      channel: '#craftirctest'
    filters:
      - type: antihighlight
        splitter: " "
        variable: SENDER_NAME
      - type: datamapper
        message: "<%SENDER_NAME%> %MESSAGE_TEXT%"
      - type: regex
        pattern: "butts"
        value: MESSAGE_TEXT
        action: drop
bots:
  - name: bot
    nick: mbaxtest
    host: irc.esper.net
links:
  - source: Game
    target: IRC